# Mystic Wands Configuration

# Mana Settings
mana:
  max-mana: 100
  regen-rate: 2  # Mana regenerated every 2 seconds
  regen-interval: 40  # Ticks (20 ticks = 1 second)

# Spell Settings
spells:
  fireball:
    mana-cost: 20
    cooldown: 3
    power: 2.0
  
  lightning:
    mana-cost: 25
    cooldown: 5
    range: 50
  
  teleport:
    mana-cost: 30
    cooldown: 10
    max-range: 100
  
  heal:
    mana-cost: 15
    cooldown: 8
    heal-amount: 6
  
  freeze:
    mana-cost: 20
    cooldown: 6
    radius: 5
    duration: 100  # Ticks
  
  explosion:
    mana-cost: 40
    cooldown: 15
    power: 4.0
    break-blocks: true

# General Settings
general:
  show-mana-bar: true
  spell-particles: true
  spell-sounds: true